export const nivelAprobacionPorMovimiento: Record<string, number> = {
  "Cambio de horario": 1,
  "Comisión fuera de Oficina": 1,
  "Comisión Prolongada fuera de Oficina": 2,
  "Curso/Capacitación": 1,
  "Descanso laborado": 2,
  "Descanso por comisión laboral": 1,
  "Falta justificada IMSS": 1,
  "Horario de Lactancia": 1,
  "Junta de trabajo": 1,
  "Permisos Especiales": 2,
  "Permiso con goce de sueldo": 2,
  "Permiso para llegar tarde": 1,
  "Permiso sin goce de sueldo": 1,
  "Retardo justificado": 1,
  "Salida anticipada": 1,
  "Sin registro entrada": 1,
  "Sin registro salida": 1,
  "Tiempo extra": 2,
  "Viaje de Trabajo": 1,
  "extraoridinario": 1,
};

export const movements = [
  "Cambio de descanso",
  "Cambio de horario",
  "Comisión fuera de Oficina",
  "Comisión Prolongada fuera de Oficina",
  "Curso/Capacitación",
  "Descanso laborado",
  "Descanso por comisión laboral",
  "Falta justificada IMSS",
  "Horario de Lactancia",
  "Junta de trabajo",
  "Permisos Especiales",
  "Permiso con goce de sueldo",
  "Permiso para llegar tarde",
  "Permiso sin goce de sueldo",
  "Retardo justificado",
  "Salida anticipada",
  "Sin registro entrada",
  "Sin registro salida",
  "Tiempo extra",
  "Viaje de Trabajo",
  "extraoridinario",
];

export const opcionesPorIncidencia: Record<string, string[]> = {
  "Falta": [
    "Comisión fuera de Oficina",
    "Comisión Prolongada fuera de Oficina",
    "Falta justificada IMSS",
    "Permisos Especiales",
    "Permiso con goce de sueldo",
    "Permiso sin goce de sueldo",
    "Descanso laborado",
    "Descanso por comisión laboral",
  ],
  "No Chec¢ Entrada": [
    "Retardo justificado",
    "Permiso para llegar tarde",
    "Sin registro entrada",
  ],
  "No Chec¢ Salida": [
    "Salida anticipada",
    "Sin registro salida",
  ],
  "Retardo E1": [
    "Retardo justificado",
    "Permiso para llegar tarde",
  ]
};
