export const puestos = [
  "Administrador de compras",
  "Administrador de ventas de piso",
  "Administrador de ventas tienda",
  "Admr. de crédito y cobranza tiendas",
  "Almacenista",
  "Almacenista sucursal central",
  "Analista Comercio Exterior",
  "Analista contable",
  "Analista de costos",
  "Analista de Crédito y Cobranza",
  "Analista de cuentas por pagar",
  "Analista de Exportaciones",
  "Analista de invetarios",
  "Analista de Tesorería",
  "Analista de Viaticos",
  "Analista Fiscal",
  "Analista investigación estadística y me",
  "Asistente de Dirección",
  "Auditor Interno",
  "Aux. admvo. Imp. Exp. y Ce.",
  "Auxiliar de Compras",
  "Auxiliar administrativo de compras Nacio",
  "Auxiliar contable",
  "Auxiliar de asistente de direción",
  "Auxiliar de atracción de talento",
  "Auxiliar de Calidad",
  "Auxiliar de Capital Humano",
  "Auxiliar de Cobranza Tiendas",
  "Auxiliar de Compras Nacionales",
  "Auxiliar de Control de Documentos",
  "Auxiliar de Costos",
  "Auxiliar de Inventarios",
  "Auxiliar de Inventarios pisos",
  "Auxiliar de inventarios sucursales",
  "Auxiliar de Logística Nacional",
  "Auxiliar de Tesorería",
  "Auxiliar de venta y servicio al cliente",
  "Auxiliar operativo de inventarios",
  "Auxiliar operativo ventas piso",
  "Cajera",
  "Cargador",
  "Chofer",
  "Chofer Foraneo",
  "Cobrador Locoal",
  "Comprador de Campo",
  "Comprador Jr.",
  "Comprador Sr.",
  "Contador de egresos y costos",
  "Contador de ingresos",
  "Coord. de Importaciones Marítimas Aéreas",
  "Coord. de Sistema de Gestión de Calidad",
  "Coordinador Administrativo Operativo",
  "Coordinador Administrativo Suc.",
  "Coordinador de admin. de ventas tienda",
  "Coordinador de asuntos legales y Admr.",
  "Coordinador de atracción de talento",
  "Coordinador de Calidad Llegadas",
  "Coordinador de calidad prod. almacenado",
  "Coordinador de Compensaciones",
  "Coordinador de compras nacionales",
  "Coordinador de Cuentas por Pagar",
  "Coordinador de Desarrollo Organizacional",
  "Coordinador de Importaciones Terrestres",
  "Coordinador de Inventarios",
  "Coordinador de LN de compras e imp",
  "Coordinador de LN de compras y exp.",
  "Coordinador de LN en ventas",
  "Coordinador de Logística Local",
  "Coordinador de Logística Local Pisos",
  "Coordinador de relaciones laborales",
  "Coordinador Operaciones de Exportación",
  "Coordinador operativo",
  "Coordinador operativo de almacen",
  "Coordinador Operativo de Inventarios Suc",
  "Dirección General",
  "Director de Admon y Finanzas",
  "Director de Comercialización Ventas Piso",
  "Diseñador integral y Mkt",
  "Ejecutivo de compras",
  "Ejecutivo de ventas cedis",
  "Ejecutivo de ventas exportaciones",
  "Ejecutivo de Ventas Tiendas",
  "Encargado de Almacen Insumos",
  "Gerente Comercual",
  "Gerente de Compras Nacionales",
  "Gerente de desarrollo de Nuevos Negocios",
  "Gerente de Operaciones",
  "Gerente de Recursos Humanos",
  "Gerente de Sistemas",
  "Gerente de ventas tienda",
  "Gte. de Planeación e Inteligencia del Mer",
  "Ingeniero de aplicaciones",
  "Ingeniero de infraestructura",
  "Ingeniero de soporte ERP",
  "Ingeniero Desarrollo Jr",
  "Inspector de calidad de pisos",
  "Inspector Calidad Llegadas",
  "Inspector de calidad de campo y exportaciones",
  "Inspector de Calidad Producto Almacenado",
  "Inspector de Calidad Reempaque",
  "Inpector de calidad sucursal",
  "Jefe de Calidad",
  "Jefe de cuentas por pagar",
  "Jefe de exportaciones",
  "Jefe de importaciones",
  "Jefe de importaciones export. y CE",
  "Jefe de Inventarios",
  "Jefe de Logística Local",
  "Jefe de Logística Nacional",
  "Jefe de mercadotecnia",
  "Jefe de proyectos",
  "Jefe de ventas piso",
  "Monitorista",
  "Paramedico",
  "Sub Jefe de Ventas Piso",
  "Supervisor de Cobranza pisos",
  "Tecnico en equipo de transporte",
  "Tecnico en instalaciones",
  "Tecnico en soporte",
  "Tecnico en soporte infraestructura",
  "Temp. Auxiliar operativo ventas piso",
  "Temp. Chófer",
  "Vendedor",
  "Vendedor Foráneo",
  "Verificador de Salida de Mercancía",
  "Analista Administrativo",
  "Coordinador de Mantenimiento",
  "Auditor",
  "Coordinador de Inventarios Insumos"
];